#!/bin/bash
die() { echo $* >&2; exit 1; }

cpu=atmega328p
serial=($(shopt -s nullglob; echo /dev/serial/by-id/usb-Arduino* /dev/ttyACM0))

while getopts ":c:s:" o; do case $o in
    c) cpu=$OPTARG;;   
    s) serial=$OPTARG;;
esac; done
shift $((OPTIND-1))

(($#)) || die "Usage: download [-s serial-device] [-c cpu] image[.hex]"

image=$1
[[ -f $image ]] || image+=".hex"
[[ -f $image ]] || die "No such file $image"

avrdude -q -c arduino -p "$cpu" -P "$serial" -b 115200 -U "flash:w:$image:i"
